export const CREATE_POPUP = "CREATE_POPUP";

export const CREATE_WORKSPACE_POPUP = "CREATE_WORKSPACE_POPUP";

export const CREATE_BOARD_POPUP = "CREATE_BOARD_POPUP";

export const CHANGE_WORKSPACE = "CHANGE_WORKSPACE";

export const ADD_NEW_CARD = "ADD_NEW_CARD";

export const ADD_NEW_LIST = "ADD_NEW_LIST";
