export const CREATE_POPUP = 'CREATE_POPUP';

export const CREATE_WORKSPACE_POPUP = 'CREATE_WORKSPACE_POPUP';

export const CREATE_BOARD_POPUP = 'CREATE_BOARD_POPUP';

export const CHANGE_WORKSPACE = 'CHANGE_WORKSPACE';

export const ACCOUNT_POPUP = 'ACCOUNT_POPUP';

export const ADD_NEW_CARD = 'ADD_NEW_CARD';

export const ADD_NEW_LIST = 'ADD_NEW_LIST';

export const NAVIGATE_TO_HOME = 'NAVIGATE_TO_HOME';

export const NAVIGATE_TO_BOARD = 'NAVIGATE_TO_BOARD';

export const SET_DATA = 'SET_DATA';

export const ADD_NEW_CARD_ITEM = 'ADD_NEW_CARD_ITEM';

export const ADD_NEW_LIST_ITEM = 'ADD_NEW_LIST_ITEM';

export const ORDER_LIST = 'ORDER_LIST';

export const ORDER_CARD = 'ORDER_CARD';

export const LIST_NAME_EDIT = 'LIST_NAME_EDIT';

export const CARD_NAME_EDIT = 'CARD_NAME_EDIT';

export const LIST_DELETE = 'LIST_DELETE';

export const CARD_DELETE = 'CARD_DELETE';
